### ISSUE TITLE
[feature] Implement Analytics core

### ISSUE THREAD

**Issue by Sam-Newman** [WalletConnect/web3modal-react-native#138]
## Description
Implement the base logic to make it possible to send events to the analytics API

## Tasks
- [ ] Add the EventsController to the core package
- [ ] Add a new SDK option to enable/disable analytics
- [ ] Send MODAL_LOADED event

## Related Issues
N/A
