### ISSUE TITLE
[feature] Send basic events to API

### ISSUE THREAD

**Issue by Sam-Newman** [WalletConnect/web3modal-react-native#140]
## Description
Send events to the analytics api using the EventsController

## Tasks
- [ ] Implement basic events:
  - [ ]   MODAL_LOADED
  - [ ]   MODAL_OPEN
  - [ ]   MODAL_CLOSE
  - [ ]   CLICK_ALL_WALLETS
  - [ ]   SELECT_WALLET
  - [ ]   CLICK_NETWORKS
  - [ ]   OPEN_ACTIVITY_VIEW
  - [ ]   SWITCH_NETWORK
  - [ ]   CONNECT_SUCCESS
  - [ ]   CONNECT_FAILURE
  - [ ]   DISCONNECT_SUCCESS
  - [ ]   DISCONNECT_ERROR
  - [ ]   CLICK_WALLET_HELP
  - [ ]   CLICK_NETWORK_HELP
  - [ ]   CLICK_GET_WALLET

## Related Issues
Link to Analytics core task
