### ISSUE TITLE
[Epic] Milestone 1: RN SDK

### ISSUE THREAD

**Issue by ignaciosantise** [WalletConnect/web3modal-react-native#19]
## Implementation Path
This is intended as an overview of critical path work for the Web3Modal React-Native SDK, from which we can break out concrete and more detailed individual issues. The list may change and reorder as we see necessary during the development process.

### Features

- [x] Show mobile wallets list from Explorer API
- [x] Show QR Code
- [x] Customizable cloud PROJECT_ID
- [x] Connect with Wallet
- [x] Add Eth_methods to example
- [x] https://github.com/WalletConnect/web3modal-react-native/pull/20
- [x] https://github.com/WalletConnect/web3modal-react-native/pull/21
- [x] Update docs

### Issues to be solved
- [x] https://github.com/WalletConnect/web3modal-react-native/issues/13

### Next steps
https://github.com/WalletConnect/web3modal-react-native/issues/27
