### ISSUE TITLE
[Epic] Milestone 2: RN SDK

### ISSUE THREAD

**Issue by ignaciosantise** [WalletConnect/web3modal-react-native#27]
## Implementation Path
This is intended as an overview of critical path work for the Web3Modal React-Native SDK, from which we can break out concrete and more detailed individual issues. The list may change and reorder as we see necessary during the development process.

### Features

- [x] https://github.com/WalletConnect/web3modal-react-native/issues/42
- [x] [Adapt views to Light/Dark theme](https://github.com/WalletConnect/web3modal-react-native/pull/45)
- [x] https://github.com/WalletConnect/web3modal-react-native/issues/52
- [x] https://github.com/WalletConnect/web3modal-react-native/pull/55
- [x] Improve animations: https://github.com/WalletConnect/web3modal-react-native/pull/56
- [ ] [explorerRecommendedWalletIds](https://docs.walletconnect.com/2.0/web/web3modal/react/wagmi/options#explorerrecommendedwalletids-optional)
- [ ] [explorerExcludedWalletIds](https://docs.walletconnect.com/2.0/web/web3modal/react/wagmi/options#explorerexcludedwalletids-optional)
- [ ] Add search bar in wallet screen
- [ ] Add “What is a wallet” screen
- [ ] Improve Connect Button
- [ ] Add reload screen if wallet list fails
- [ ] Show balance in Account view
- [ ] Show chain info in Account view
- [ ] Chain select in Account View + Search bar
   - Define list of chains
- [ ] https://github.com/WalletConnect/web3modal-react-native/issues/16
- [ ] Update docs

### Issues to be solved
- [ ] `No matching key` warning

### Next steps
TBD

**Comment by kacperoak** [comment]
LGTM but I would like to know more about `Chain select`. Do we have a description of this functionality? I would like to understand this to know how to transfer it to my sdk.
